#!/bin/bash

# This script tags and pushes a locally existent docker image to a specified
# new tag. It expects the environment variables DOCKER_USERNAME and
# DOCKER_PASSWORD to be set.

set -e -u

if [[ $# -ne 2 ]]; then
	echo "usage: $0 <local_tag> <push_tag>" >&2
	exit 2
fi
LOCAL_TAG=$1
PUSH_TAG=$2

docker tag "${LOCAL_TAG}" "${PUSH_TAG}"
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
echo "pushing image to repository ${PUSH_TAG}"
docker push "${PUSH_TAG}"
docker logout
